"""add timezones, alternative spellings and demonym in Country Table

Revision ID: 57649f538f53
Revises: e1e65e704a8b
Create Date: 2026-02-10 09:34:48.102200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57649f538f53'
down_revision: Union[str, Sequence[str], None] = 'e1e65e704a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('country', sa.Column('alt_spellings', sa.String(length=500), nullable=True))
    op.add_column('country', sa.Column('female_demonym', sa.String(length=100), nullable=True))
    op.add_column('country', sa.Column('male_demonym', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'male_demonym')
    op.drop_column('country', 'female_demonym')
    op.drop_column('country', 'alt_spellings')
    op.drop_column('country', 'timezone')
    # ### end Alembic commands ###
