"""Remove driver's grid number and driver's team_id

Revision ID: 80cb15bd8df8
Revises: e3e2ab44eaba
Create Date: 2026-02-10 15:20:24.807262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cb15bd8df8'
down_revision: Union[str, Sequence[str], None] = 'e3e2ab44eaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('driver_team_id_fkey'), 'driver', type_='foreignkey')
    op.drop_column('driver', 'grid_number')
    op.drop_column('driver', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('driver', sa.Column('grid_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('driver_team_id_fkey'), 'driver', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
