"""Remove track's timezone (already in country's table)

Revision ID: cde6da21db21
Revises: 80cb15bd8df8
Create Date: 2026-02-10 17:01:41.365556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde6da21db21'
down_revision: Union[str, Sequence[str], None] = '80cb15bd8df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
